config/routes.rb
Rails.application.routes.draw do

  resources :usuarios
  root 'apartamentos#index'

  resources :sesiones
  resources :vehiculos
  resources :residentes
  resources :apartamentos

end

app/models/apartamento.rb
class Apartamento < ActiveRecord::Base
	include Export
	has_many :vehiculos
	has_many :residentes

	validates :numero, presence: true
	validates :torre, presence: true
	validates :piso, presence: true
	validates :area, numericality: { greater_than: 0 } 

	def valor_administracion
		area * 2300
	end

	def self.methods_to_export
		super + ['valor_administracion']
	end

end

app/controllers/apartamentos_controller.rb
class ApartamentosController < ApplicationController
  before_action :authenticate
  before_action :set_apartamento, only: [:show, :edit, :update, :destroy]

  # GET /apartamentos
  # GET /apartamentos.json
  def index
    @apartamentos = Apartamento.all
    respond_to do |format|
      format.html
      format.csv { send_data Apartamento.to_csv }
      format.json
    end
  end

  # GET /apartamentos/1
  # GET /apartamentos/1.json
  def show
  end

  # GET /apartamentos/new
  def new
    @apartamento = Apartamento.new
  end

  # GET /apartamentos/1/edit
  def edit
  end

  # POST /apartamentos
  # POST /apartamentos.json
  def create
    @apartamento = Apartamento.new(apartamento_params)

    respond_to do |format|
      if @apartamento.save
        format.html { redirect_to @apartamento, notice: 'Apartamento was successfully created.' }
        format.json { render :show, status: :created, location: @apartamento }
      else
        format.html { render :new }
        format.json { render json: @apartamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartamentos/1
  # PATCH/PUT /apartamentos/1.json
  def update
    respond_to do |format|
      if @apartamento.update(apartamento_params)
        format.html { redirect_to @apartamento, notice: 'Apartamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartamento }
      else
        format.html { render :edit }
        format.json { render json: @apartamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartamentos/1
  # DELETE /apartamentos/1.json
  def destroy
    @apartamento.destroy
    respond_to do |format|
      format.html { redirect_to apartamentos_url, notice: 'Apartamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartamento
      @apartamento = Apartamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartamento_params
      params.require(:apartamento).permit(:numero, :torre, :piso, :area)
    end
end

app/helpers/apartamentos_helper.rb
module ApartamentosHelper
end

app/views/apartamentos/_form.html.erb
<%= form_for(@apartamento) do |f| %>
  <% if @apartamento.errors.any? %>
    <div id="error_explanation">
      <h2><%=  t('errors.template.header', model: 'Apartamento', count: @apartamento.errors.count) %></h2>

      <ul>
      <% @apartamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">  
    
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :numero %><br>
        <%= f.text_field :numero, class: 'form-control' %>
      </div>  
    </div>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="form-group">
        <%= f.label :torre %><br>
        <%= f.text_field :torre, class: 'form-control' %>
      </div>  
    </div>
    <div class="col-md-4 col-sm-6 col-xs-6">
      <div class="form-group">
        <%= f.label :piso %><br>
        <%= f.number_field :piso, class: 'form-control'%>
      </div>  
    </div>
    <div class="col-md-4 col-sm-6 col-xs-6">
      <div class="form-group">
        <%= f.label :area %><br>
        <%= f.number_field :area, class: 'form-control' %>
      </div> 
    </div>  

  </div>



  
  
  
  
  <div class="actions">
    <%= f.submit 'Guardar', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/apartamentos/edit.html.erb
<h1>Editing Apartamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartamento %> |
<%= link_to 'Back', apartamentos_path %>

app/views/apartamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Listing Apartamentos</h4>

<table class="table table-striped table-condensed table-hover">
  <thead>
    <tr>
      <th>Numero</th>
      <th>Torre</th>
      <th>Piso</th>
      <th>Area</th>
      <th>Nro habitantes</th>
      <th>Nro vehículos</th>
      <th>Valor Administración</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartamentos.each do |apartamento| %>
      <tr>
        <td><%= apartamento.numero %></td>
        <td><%= apartamento.torre %></td>
        <td><%= apartamento.piso %></td>
        <td><%= apartamento.area %></td>
        <td><%= apartamento.residentes.count %></td>
        <td><%= apartamento.vehiculos.count %></td>
        <td><%= apartamento.valor_administracion %></td>
        <td><%= link_to 'Show', apartamento %></td>
        <td><%= link_to 'Edit', edit_apartamento_path(apartamento) %></td>
        <td><%= link_to 'Destroy', apartamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apartamento', new_apartamento_path, class: 'btn btn-primary' %>

app/views/apartamentos/new.html.erb
<h1>New Apartamento</h1>

<%= render 'form' %>

<%= link_to 'Back', apartamentos_path %>

app/views/apartamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @apartamento.numero %>
</p>

<p>
  <strong>Torre:</strong>
  <%= @apartamento.torre %>
</p>

<p>
  <strong>Piso:</strong>
  <%= @apartamento.piso %>
</p>

<p>
  <strong>Area:</strong>
  <%= @apartamento.area %>
</p>

<p>
  <strong>Nro habitantes:</strong>
  <%= @apartamento.residentes.count %>
</p>

<p>
  <strong>Nro vehículos:</strong>
  <%= @apartamento.vehiculos.count %>
</p>

<p>
  <strong>Valor administración:</strong>
  <%= @apartamento.valor_administracion %>
</p>

<%= link_to 'Edit', edit_apartamento_path(@apartamento) %> |
<%= link_to 'Back', apartamentos_path %>