config/routes.rb
Rails.application.routes.draw do

  resources :usuarios
  root 'apartamentos#index'

  resources :sesiones
  resources :vehiculos
  resources :residentes
  resources :apartamentos

end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
	include Export
  belongs_to :apartamento

  validates :placa, presence: true, uniqueness: true
  validates :marca , presence: true
  validates :color, presence: true
  validates :descripcion, length: { maximum: 50}
end

app/controllers/vehiculos_controller.rb
class VehiculosController < ApplicationController
  before_action :authenticate
  before_action :set_vehiculo, only: [:show, :edit, :update, :destroy]

  # GET /vehiculos
  # GET /vehiculos.json
  def index
    @vehiculos = Vehiculo.all
    respond_to do |format|
      format.html
      format.csv { send_data Vehiculo.to_csv }
      format.json
    end
  end

  # GET /vehiculos/1
  # GET /vehiculos/1.json
  def show
  end

  # GET /vehiculos/new
  def new
    @vehiculo = Vehiculo.new
  end

  # GET /vehiculos/1/edit
  def edit
  end

  # POST /vehiculos
  # POST /vehiculos.json
  def create
    @vehiculo = Vehiculo.new(vehiculo_params)

    respond_to do |format|
      if @vehiculo.save
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully created.' }
        format.json { render :show, status: :created, location: @vehiculo }
      else
        format.html { render :new }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehiculos/1
  # PATCH/PUT /vehiculos/1.json
  def update
    respond_to do |format|
      if @vehiculo.update(vehiculo_params)
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehiculo }
      else
        format.html { render :edit }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehiculos/1
  # DELETE /vehiculos/1.json
  def destroy
    @vehiculo.destroy
    respond_to do |format|
      format.html { redirect_to vehiculos_url, notice: 'Vehiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehiculo
      @vehiculo = Vehiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehiculo_params
      params.require(:vehiculo).permit(:placa, :marca, :color, :descripcion, :apartamento_id)
    end
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/vehiculos/_form.html.erb
<%= form_for(@vehiculo) do |f| %>
<% if @vehiculo.errors.any? %>
<div id="error_explanation">
  <h2><%=  t('errors.template.header', model: 'Vehiculo', count: @vehiculo.errors.count) %></h2>

  <ul>
    <% @vehiculo.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :placa %><br>
      <%= f.text_field :placa , class: 'form-control'%>
    </div>
  </div>
  
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :marca %><br>
      <%= f.text_field :marca , class: 'form-control'%>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :color %><br>
      <%= f.text_field :color, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :descripcion %><br>
      <%= f.text_area :descripcion, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :apartamento_id %><br>
      <%= f.collection_select :apartamento_id, Apartamento.all, :id, :numero  %>
    </div>
  </div>
</div>
<div class="actions">
  <%= f.submit 'Guardar', class: 'btn btn-success'%>
</div>
<% end %>

app/views/vehiculos/edit.html.erb
<h1>Editing Vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehiculo %> |
<%= link_to 'Back', vehiculos_path %>

app/views/vehiculos/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Listing Vehiculos</h4>

<table class="table table-striped table-condensed table-hover">
  <thead>
    <tr>
      <th>Placa</th>
      <th>Marca</th>
      <th>Color</th>
      <th>Descripcion</th>
      <th>Apartamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehiculos.each do |vehiculo| %>
      <tr>
        <td><%= vehiculo.placa %></td>
        <td><%= vehiculo.marca %></td>
        <td><%= vehiculo.color %></td>
        <td><%= vehiculo.descripcion %></td>
        <td><%= vehiculo.apartamento.numero %></td>
        <td><%= link_to 'Show', vehiculo %></td>
        <td><%= link_to 'Edit', edit_vehiculo_path(vehiculo) %></td>
        <td><%= link_to 'Destroy', vehiculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehiculo', new_vehiculo_path, class: 'btn btn-primary' %>

app/views/vehiculos/new.html.erb
<h1>New Vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Back', vehiculos_path %>

app/views/vehiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Placa:</strong>
  <%= @vehiculo.placa %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @vehiculo.marca %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehiculo.color %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @vehiculo.descripcion %>
</p>

<p>
  <strong>Apartamento:</strong>
  <%= @vehiculo.apartamento.numero %>
</p>

<%= link_to 'Edit', edit_vehiculo_path(@vehiculo) %> |
<%= link_to 'Back', vehiculos_path %>