config/routes.rb
Rails.application.routes.draw do

  resources :usuarios
  root 'apartamentos#index'

  resources :sesiones
  resources :vehiculos
  resources :residentes
  resources :apartamentos

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
	include Export
	validates :nombre, presence: true
	validates :apellido, presence: true
	validates :login, presence: true, uniqueness: true
	validates :correo, presence: true, uniqueness: true
	validates :correo, format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	has_secure_password

	after_update :send_updated_mail
	after_create :send_created_mail


	def send_created_mail
	  UserMailer.created(id).deliver
	end

	def send_updated_mail
	  UserMailer.updated(id).deliver
	end

	def self.authenticate(email = '', password = '')
		user = find_by("correo = :mail or login = :mail", mail: email)
		user && user.authenticate(password)
	end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :authenticate
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
    respond_to do |format|
      format.html
      format.csv { send_data Usuario.to_csv }
      format.json
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :login, :password, :password_confirnation, :correo)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
<% if @usuario.errors.any? %>
<div id="error_explanation">
  <h2><%=  t('errors.template.header', model: 'Usuario', count: @usuario.errors.count) %></h2>

  <ul>
    <% @usuario.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="row">
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :nombre %><br>
      <%= f.text_field :nombre , class: 'form-control'%>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :apellido %><br>
      <%= f.text_field :apellido , class: 'form-control'%>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :login %><br>
      <%= f.text_field :login , class: 'form-control'%>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :password %><br>
      <%= f.text_field :password, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :password_confirmation %><br>
      <%= f.text_field :password_confirmation , class: 'form-control'%>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :correo %><br>
      <%= f.text_field :correo, class: 'form-control' %>
    </div>
  </div>
</div>
<div class="actions">
  <%= f.submit 'Guardar', class: 'btn btn-success'%>
</div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Listing Usuarios</h4>

<table class="table table-striped table-condensed table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Login</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.login %></td>
        <td><%= usuario.correo %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path, class: 'btn btn-primary' %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @usuario.apellido %>
</p>

<p>
  <strong>Login:</strong>
  <%= @usuario.login %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @usuario.correo %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>