config/routes.rb
Rails.application.routes.draw do

  resources :usuarios
  root 'apartamentos#index'

  resources :sesiones
  resources :vehiculos
  resources :residentes
  resources :apartamentos

end

app/models/residente.rb
class Residente < ActiveRecord::Base
	include Export
  belongs_to :apartamento

  after_create :incrementar_residente

  validates :nombre, presence: true
  validates :identificacion, presence: true, uniqueness: true
  validates :apellido, presence: true

  def incrementar_residente
  	apartamento.nro_habitantes += 1
  	apartamento.save
  end


end

app/controllers/residentes_controller.rb
class ResidentesController < ApplicationController
  before_action :authenticate
  before_action :set_residente, only: [:show, :edit, :update, :destroy]

  # GET /residentes
  # GET /residentes.json
  def index
    @residentes = Residente.all
    respond_to do |format|
      format.html
      format.csv { send_data Residente.to_csv }
      format.json
    end
  end

  # GET /residentes/1
  # GET /residentes/1.json
  def show
  end

  # GET /residentes/new
  def new
    @residente = Residente.new
  end

  # GET /residentes/1/edit
  def edit
  end

  # POST /residentes
  # POST /residentes.json
  def create
    @residente = Residente.new(residente_params)

    respond_to do |format|
      if @residente.save
        format.html { redirect_to @residente, notice: 'Residente was successfully created.' }
        format.json { render :show, status: :created, location: @residente }
      else
        format.html { render :new }
        format.json { render json: @residente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residentes/1
  # PATCH/PUT /residentes/1.json
  def update
    respond_to do |format|
      if @residente.update(residente_params)
        format.html { redirect_to @residente, notice: 'Residente was successfully updated.' }
        format.json { render :show, status: :ok, location: @residente }
      else
        format.html { render :edit }
        format.json { render json: @residente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residentes/1
  # DELETE /residentes/1.json
  def destroy
    @residente.destroy
    respond_to do |format|
      format.html { redirect_to residentes_url, notice: 'Residente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_residente
      @residente = Residente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def residente_params
      params.require(:residente).permit(:nombre, :apellido, :telefono, :fecha_nacimiento, :identificacion, :apartamento_id)
    end
end

app/helpers/residentes_helper.rb
module ResidentesHelper
end

app/views/residentes/_form.html.erb
<%= form_for(@residente) do |f| %>
<% if @residente.errors.any? %>
<div id="error_explanation">
  <h2><%=  t('errors.template.header', model: 'Residente', count: @residente.errors.count) %></h2>

  <ul>
    <% @residente.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :nombre %><br>
      <%= f.text_field :nombre, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :apellido %><br>
      <%= f.text_field :apellido, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :telefono %><br>
      <%= f.text_field :telefono, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :fecha_nacimiento %><br>
      <%= f.date_select :fecha_nacimiento , class: 'form-control'%>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :identificacion %><br>
      <%= f.text_field :identificacion, class: 'form-control' %>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="form-group">
      <%= f.label :apartamento_id %><br>
      <%= f.collection_select :apartamento_id, Apartamento.all, :id, :numero  %>
    </div>
  </div>
</div>
<div class="actions">
  <%= f.submit'Guardar', class: 'btn btn-success' %>
</div>
<% end %>

app/views/residentes/edit.html.erb
<h1>Editing Residente</h1>

<%= render 'form' %>

<%= link_to 'Show', @residente %> |
<%= link_to 'Back', residentes_path %>

app/views/residentes/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Listing Residentes</h4>

<table class="table table-striped table-condensed table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Telefono</th>
      <th>Fecha nacimiento</th>
      <th>Identificacion</th>
      <th>Apartamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @residentes.each do |residente| %>
      <tr>
        <td><%= residente.nombre %></td>
        <td><%= residente.apellido %></td>
        <td><%= residente.telefono %></td>
        <td><%= residente.fecha_nacimiento %></td>
        <td><%= residente.identificacion %></td>
        <td><%= residente.apartamento.numero %></td>
        <td><%= link_to 'Show', residente %></td>
        <td><%= link_to 'Edit', edit_residente_path(residente) %></td>
        <td><%= link_to 'Destroy', residente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Residente', new_residente_path, class: 'btn btn-primary' %>

app/views/residentes/new.html.erb
<h1>New Residente</h1>

<%= render 'form' %>

<%= link_to 'Back', residentes_path %>

app/views/residentes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @residente.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @residente.apellido %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @residente.telefono %>
</p>

<p>
  <strong>Fecha nacimiento:</strong>
  <%= @residente.fecha_nacimiento %>
</p>

<p>
  <strong>Identificacion:</strong>
  <%= @residente.identificacion %>
</p>

<p>
  <strong>Apartamento:</strong>
  <%= @residente.apartamento.numero %>
</p>

<%= link_to 'Edit', edit_residente_path(@residente) %> |
<%= link_to 'Back', residentes_path %>